version: "2"
networks:
  project:
    external: false
volumes:
  data:
services:
  fpm:
    build:
      context: ./fpm
    networks:
      - project
    volumes:
      - data:/data/
    environment:
      PHAB_HOST: ${PHAB_HOST}
      PHAB_WEB_PORT: ${PHAB_WEB_PORT}
      PHAB_SSH_PORT: ${PHAB_SSH_PORT}
  sshd:
    build:
      context: ./sshd
    networks:
      - project
    volumes:
      - data:/data/
  phd:
    build:
      context: ./phd
    networks:
      - project
    volumes:
      - data:/data/
  nginx:
    depends_on:
      - fpm
    image: nginx:1.16-alpine
    networks:
      - project
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  noty:
    image: modicn/phabricator:noty
    networks:
      - project
