version: "2"
services:
  envoy:
    image: envoyproxy/envoy-alpine:v1.12-latest
    networks:
      project:
        aliases:
          - p.localhost
    volumes:
      - ./envoy/envoy.yml:/etc/envoy/envoy.yaml
    ports:
      - 8181:8181
      - 2222:2222
      - 22280:22280
