version: '2'
networks:
  project:
    external: false
volumes:
  mysql_data:
  data:
  conf:
services:
  mysql:
    image: mysql:5.7
    networks:
      - project
    volumes:
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/zz.cnf
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  fpm:
    depends_on:
      - mysql
    build:
      context: ./fpm
    user: phab
    networks:
      - project
    volumes:
      - data:/data/
      - conf:/code/phabricator/conf/local/
    environment:
      PHAB_HOST: ${PHAB_HOST}
      PHAB_WEB_PORT: ${PHAB_WEB_PORT}
      PHAB_SSH_PORT: ${PHAB_SSH_PORT}
  sshd:
    build:
      context: ./sshd
    networks:
      - project
    volumes:
      - data:/data/
      - conf:/code/phabricator/conf/local/
  phd:
    build:
      context: ./phd
    user: phab
    networks: 
      - project
    volumes:
      - data:/data/
      - conf:/code/phabricator/conf/local/
  nginx:
    depends_on:
      - fpm
    image: nginx:1.16-alpine
    networks:
      - project
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  noty:
    image: modicn/phabricator:noty
    networks:
      - project
  envoy:
    image: envoyproxy/envoy-alpine:v1.12-latest
    networks:
      project:
        aliases:
          - ${PHAB_HOST}
    volumes:
      - ./envoy/envoy.yml:/etc/envoy/envoy.yaml
    ports:
      - ${PHAB_WEB_PORT}:8801
      - ${PHAB_SSH_PORT}:2201
      - ${PHAB_WS_PORT}:22280
