version: '2'
networks:
  project:
    external: false
volumes:
  mysql_data:
  repos:
  files:
  phd:
  conf:
services:
  mysql:
    image: mysql:5.7.24
    networks:
      - project
    volumes:
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/zz.cnf
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  fpm:
    image: modicn/phabricator:fpm
    networks:
      - project
    volumes:
      - repos:/data/repos
      - files:/data/files
      - phd:/run/phd
      - conf:/code/phabricator/conf/local
    environment:
      PHAB_HOST: ${PHAB_HOST}
  sshd:
    image: modicn/phabricator:sshd
    networks:
      - project
    volumes:
      - repos:/data/repos
      - files:/data/files
      - phd:/run/phd
      - conf:/code/phabricator/conf/local
  phd:
    image: modicn/phabricator:phd
    networks: 
      - project
    volumes:
      - repos:/data/repos
      - files:/data/files
      - phd:/run/phd
      - conf:/code/phabricator/conf/local
  nginx:
    depends_on:
      - fpm
    image: nginx:1.16-alpine
    networks:
      - project
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  noty:
    image: modicn/phabricator:noty
    networks:
      - project
  envoy:
    image: envoyproxy/envoy-alpine:v1.12.2
    networks:
      project:
        aliases:
          - ${PHAB_HOST}
    volumes:
      - ./envoy/envoy.yml:/etc/envoy/envoy.yaml
