version: '2'
networks:
  project:
    external: false
volumes:
  mysql_data:
  storage:
  conf:
services:
  mysql:
    image: mysql:5.7.24
    networks:
      - project
    volumes:
      - ./conf/mysql/mysql.cnf:/etc/mysql/conf.d/zz.cnf
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  php:
    image: "mdxdm/phabricator:${PHAB_VER}"
    networks:
      - project
    volumes:
      - storage:/storage
      - conf:/code/phabricator/conf/local
    environment:
      PHAB_HOST: ${PHAB_HOST}
  nginx:
    depends_on:
      - php
    image: nginx:1.14.2-alpine
    networks:
      project:
        aliases:
          - ${PHAB_HOST}
    volumes:
      - ./conf/nginx/vhosts.conf:/etc/nginx/conf.d/default.conf
  front:
    image: envoyproxy/envoy-alpine:v1.11.0
    networks:
      project:
        aliases:
          - ${PHAB_HOST}
    volumes:
      - ./conf/envoy/envoy.yml:/etc/envoy/envoy.yaml
  noty:
    image: "mdxdm/phabricator-aphlict:${PHAB_VER}"
    networks:
      - project
