version: "2"
networks:
  project:
    external: false
volumes:
  data:
services:
  fpm:
    image: modicn/phabricator:fpm
    networks:
      - project
    volumes:
      - data:/data/
    environment:
      - PHA_BASE_URI=http://p.localhost:8181/
      - PHA_SSH_PORT=2222
      - PHA_DB_HOST=db
      - PHA_DB_USER=root
      - PHA_DB_PASS=root
      - PHA_APHLICT_CLIENT_HOST=p.localhost
      - PHA_APHLICT_CLIENT_PORT=22280
  ssh:
    image: modicn/phabricator:ssh
    networks:
      - project
    volumes:
      - data:/data/
  phd:
    image: modicn/phabricator:phd
    networks:
      - project
    volumes:
      - data:/data/
  aphlict:
    image: modicn/phabricator:aphlict
    networks:
      - project
  nginx:
    depends_on:
      - fpm
    image: nginx:1.16-alpine
    networks:
      - project
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
