version: "2"
networks:
  project:
    external: false
volumes:
  mysql_data:
  data:
services:
  db:
    image: mysql:5.7
    networks:
      - project
    volumes:
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/zz.cnf
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  phabricator:
    image: modicn/phabricator:supervisord
    networks:
      project:
        aliases:
          - p.localhost
    volumes:
      - data:/data/
    command: ["phabricator"]
    environment:
      - PHA_BASE_URI=http://p.localhost:8181/
      - PHA_SSH_PORT=2222
      - PHA_DB_HOST=db
      - PHA_DB_USER=root
      - PHA_DB_PASS=root
      - PHA_APHLICT_CLIENT_HOST=p.localhost
      - PHA_APHLICT_CLIENT_PORT=22280
    extra_hosts:
      aphlict: 127.0.0.1
    ports:
      - 8181:8181
      - 2222:2222
      - 22280:22280
